dist: xenial
language: python
python:
  - "3.6"


services: sqlite3

env:
  - DJANGO=2.0
  #- DJANGO=1.11.20

before_install:
  - export DJANGO_SETTINGS_MODULE=dineos_boys.settings

  - export PYTHONPATH="/home/travis/build/spmabz/time_table"
  - export PIP_USE_MIRRORS=true
  - BUILD_ON_TRAVIS=true

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install coverage
  - pip install Django
  - pip install pathlib
  - pip install django-nose
  - pip install ldap3
  - pip install selenium
  - pip install webdriver-manager


before_script:

  #- mysql -e "CREATE DATABASE travis_ci_db;"


  #- sqlite3 -e "CREATE DATABASE mydb;"


# command to run tests
script:
  - python manage.py runserver
  - python manage.py test


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls
