language: python
python:
  - "3.6"


services: mysql

env:
  - DJANGO=2.0

before_install:
  - export DJANGO_SETTINGS_MODULE=dineos_boys.settings

  - export PYTHONPATH="/home/travis/build/spmabz/time_table"
  - export PIP_USE_MIRRORS=true
  - BUILD_ON_TRAVIS=true

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install coverage
  - pip install Django==1.11.20
  - pip install pathlib


before_script:
<<<<<<< HEAD:.travis.yml
  - mysql -e "CREATE DATABASE travis_ci_db;"

=======
  #- sqlite3 -e "CREATE DATABASE mydb;"
>>>>>>> 8130911923ac40a5b211041b18bbe72d04a071ec:.travis.yml

# command to run tests
script:
  - python manage.py migrate
  - python manage.py test
  - coverage run ./Register/views.py
  - coverage run ./Register/urls.py
  #- coverage run ./Register/models.py
  #- coverage run ./Timetable/Tests/test_views.py 1

after_success:
  - coveralls
